export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as OrderList } from './OrderList'
export { default as CreateNew } from './CreateNew'
export { default as UpdateOrder } from './UpdateOrder'
export { default as Profile } from './Profile'