export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as CategoryList } from './CategoryList'
export { default as CreateNew } from './CreateNew'
export { default as UpdateCategory } from './UpdateCategory'
export { default as Profile } from './Profile'